const leads = [
  { company: 'Northstar Catering Co.', contact: 'Elena Voss', role: 'Owner / CEO', revenue: '$250,000', activity: '30m ago', status: 'active', stage: 'Term sheet', offer: '$125,000', requested: '$150,000', position: '2nd', factor: '1.32', term: '10 mo', advance: 'RapidCap · $85,000 @ 1.38', balance: '$41,200', deposits: '$250k/mo', use: 'LIC kitchen equipment + opening float', note: 'Elena walked the LIC buildout on FaceTime. Hood and fire-suppression are installed. She wants funds before Oct 1 to order equipment without stacking a third advance.', bank: [['August','$250,000','$41,220','0'],['July','$258,000','$38,640','1'],['June','$244,000','$40,110','1'],['May','$261,000','$42,840','2']], timeline: [['sms','SMS to Elena Voss — term sheet follow-up','30m ago','Asked for updated equipment invoice and delivery schedule.'],['email','Email sent — $125k term sheet','Yesterday 5:09 PM','Second-position structure sent for review.'],['call','Call Elena Voss · 12m 04s','Yesterday 2:16 PM','Confirmed October equipment deadline and vendor deposits.']] },
  { company: 'Harbor Dental Group', contact: 'Marcus Lee', role: 'Managing Partner', revenue: '$184,000', activity: '1h ago', status: 'active', stage: 'Documents in', offer: '$90,000', requested: '$100,000', position: '1st', factor: '1.29', term: '9 mo', advance: 'None', balance: '$0', deposits: '$184k/mo', use: 'New imaging suite', note: 'Statements are clean. Waiting on the signed lease addendum for the imaging room.', bank: [['August','$184,000','$29,400','0'],['July','$179,000','$25,700','0'],['June','$187,000','$31,100','0'],['May','$172,000','$22,800','1']], timeline: [['email','Email received — July and August statements','1h ago','Statements uploaded to the underwriting folder.'],['call','Call Marcus Lee · 8m 10s','Yesterday 3:30 PM','Confirmed the imaging vendor can hold pricing through Friday.'],['email','Email sent — document checklist','2d ago','Requested lease addendum and driver license.']] },
  { company: 'Saffron Market & Grill', contact: 'Amina Patel', role: 'Founder', revenue: '$118,000', activity: '1d ago', status: 'warning', stage: 'Follow-up', offer: '$65,000', requested: '$75,000', position: '1st', factor: '1.34', term: '8 mo', advance: 'BlueBridge · $32,000 @ 1.39', balance: '$18,700', deposits: '$118k/mo', use: 'Walk-in cooler replacement', note: 'Seasonal volume is improving. Two NSF items were tied to cooler repairs; request the paid invoices before final approval.', bank: [['August','$118,000','$12,300','1'],['July','$121,000','$15,100','0'],['June','$106,000','$8,900','1'],['May','$109,000','$11,400','0']], timeline: [['call','Call Amina Patel · voicemail','1d ago','Requested updated payoff letter from BlueBridge.'],['sms','SMS sent — cooler invoice follow-up','3d ago','Asked for paid invoice and vendor estimate.'],['email','Email received — August statement','5d ago','New operating statement attached.']] },
  { company: 'Summit Freight Lines', contact: 'Darius Cole', role: 'President', revenue: '$412,000', activity: '1w ago', status: 'idle', stage: 'Nurture', offer: '$0', requested: '$200,000', position: '—', factor: '—', term: '—', advance: 'Atlas Funding · $210,000', balance: '$96,500', deposits: '$412k/mo', use: 'Trailer acquisition', note: 'High revenue but multiple recent submissions. Re-engage after payoff letter and signed trailer purchase order are available.', bank: [['August','$412,000','$48,900','2'],['July','$398,000','$39,800','1'],['June','$423,000','$52,100','0'],['May','$405,000','$44,600','1']], timeline: [['email','Email sent — re-engagement','1w ago','Asked for current payoff and purchase order.'],['call','Call Darius Cole · 4m 44s','2w ago','He expects payoff figures next week.'],['email','Email received — fleet overview','3w ago','Shared trailer and route expansion plan.']] },
  { company: 'Blue Oak Home Services', contact: 'Tanya Brooks', role: 'Owner', revenue: '$96,000', activity: '1mo ago', status: 'idle', stage: 'Cold', offer: '$0', requested: '$50,000', position: '—', factor: '—', term: '—', advance: 'None', balance: '$0', deposits: '$96k/mo', use: 'Service-vehicle down payment', note: 'Initial outreach did not receive a reply. Revisit before the spring demand window.', bank: [['August','$96,000','$18,100','0'],['July','$91,000','$14,600','0'],['June','$88,000','$16,400','0'],['May','$84,000','$11,700','0']], timeline: [['email','Email sent — funding options','1mo ago','Shared a brief equipment-funding overview.'],['call','Call Tanya Brooks · voicemail','1mo ago','Left callback number.'],['email','Lead created','2mo ago','Inbound website inquiry.']] }
];
let selectedId = 0;
const leadList = document.querySelector('#leadList');
const detailPanel = document.querySelector('#detailPanel');
const activityPanel = document.querySelector('#activityPanel');
const toast = document.querySelector('#toast');
function statusLabel(status) { return status === 'active' ? 'Recently active' : status === 'warning' ? 'Needs attention' : 'No recent activity'; }
function renderLeads(query = '') {
  const needle = query.trim().toLowerCase();
  leadList.innerHTML = '';
  leads.forEach((lead, id) => {
    if (needle && ![lead.company, lead.contact, lead.role].join(' ').toLowerCase().includes(needle)) return;
    const item = document.createElement('button');
    item.type = 'button'; item.className = `lead-card ${id === selectedId ? 'selected' : ''}`;
    item.innerHTML = `<div class="lead-company">${lead.company}</div><div class="lead-meta"><span class="lead-contact">${lead.contact}</span><span class="lead-revenue">${lead.revenue}</span></div><div class="lead-activity"><span class="status-dot ${lead.status === 'active' ? '' : lead.status}" title="${statusLabel(lead.status)}" aria-label="${statusLabel(lead.status)}"></span><span>${lead.activity}</span></div>`;
    item.addEventListener('click', () => { selectedId = id; renderLeads(document.querySelector('#leadSearch').value); renderDetails(); });
    leadList.appendChild(item);
  });
}
function renderDetails() {
  const l = leads[selectedId];
  detailPanel.innerHTML = `<div class="detail-top"><div><p class="eyebrow">${l.stage}</p><h2>${l.company}</h2><p class="detail-subtitle">${l.contact} · ${l.role}</p></div><div class="status-badge"><span class="status-dot ${l.status === 'active' ? '' : l.status}"></span>${statusLabel(l.status)}</div></div><div class="detail-actions"><button class="action primary" data-action="call">Call</button><button class="action" data-action="message">Message</button><button class="action" data-action="note">Add note</button></div><div class="metric-grid"><div class="metric"><div class="metric-label">Requested</div><div class="metric-value">${l.requested}</div></div><div class="metric"><div class="metric-label">Our offer</div><div class="metric-value">${l.offer}</div></div><div class="metric"><div class="metric-label">Position</div><div class="metric-value">${l.position}</div></div></div><div class="section"><div class="section-title"><h3>Deal analysis</h3><span>${l.deposits} avg deposits</span></div><div class="note">Existing advance: ${l.advance}; remaining balance ${l.balance}. Proposed factor ${l.factor} over ${l.term}. Use of funds: ${l.use}.</div></div><div class="section"><div class="section-title"><h3>Bank & deposits</h3><span>4 months</span></div><div class="bank-table"><div class="bank-row header"><span>Month</span><span>Deposits</span><span>Ending</span><span>NSF</span></div>${l.bank.map(row => `<div class="bank-row"><span>${row[0]}</span><span>${row[1]}</span><span>${row[2]}</span><span>${row[3]}</span></div>`).join('')}</div></div><div class="section"><div class="section-title"><h3>Latest note</h3><span>${l.activity}</span></div><div class="note">${l.note}</div></div>`;
  detailPanel.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', () => showToast(`${button.textContent} action ready for ${l.contact}.`)));
  activityPanel.innerHTML = `<h2>Activity</h2><p class="subtitle">${l.company}</p><div class="timeline">${l.timeline.map(([kind,title,time,copy]) => `<article class="timeline-item"><span class="timeline-icon ${kind}"></span><div class="timeline-title">${title}</div><div class="timeline-time">${time}</div><div class="timeline-copy">${copy}</div></article>`).join('')}</div><div class="green-dot-note"><span class="status-dot"></span> Green dot = recently active: the lead has had a recent contact or activity. Gray means no recent activity; amber means follow-up needs attention.</div>`;
}
function showToast(message) { toast.textContent = message; toast.classList.add('show'); window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => toast.classList.remove('show'), 2400); }
document.querySelector('#leadSearch').addEventListener('input', event => renderLeads(event.target.value));
document.querySelector('#resetView').addEventListener('click', () => { const viewport = document.querySelector('#workspaceViewport'); viewport.scrollTo({ left: 0, top: 0, behavior: 'smooth' }); showToast('Workspace reset to the left edge.'); });
window.addEventListener('orientationchange', () => setTimeout(() => document.querySelector('#workspaceViewport').scrollBy({ left: 0, top: 0 }), 150));
renderLeads(); renderDetails();